### ISSUE TITLE
django.core.urlresolvers is deprecated

### ISSUE THREAD

**Issue by mcampbellcisco** [mjschultz/django-inviter2#14]
As of django 1.10, `django.core.urlresolvers` is deprecated in favor of `django.urls`.  This happens in 2 places here.

Patch attached: 

[urls.patch.txt](https://github.com/mjschultz/django-inviter2/files/3055936/urls.patch.txt)

**Comment by mjschultz** [comment]
Should be handled via #16 and released in [django-inviter2==1.5.0](https://pypi.org/project/django-inviter2/1.5.0/)
